/**
 * Smart EMI Pro - Advanced Export Logic
 * Handles PDF, CSV, and Excel generation with professional formatting.
 */

const ExportManager = {

    // Generate Professional PDF Report
    generatePDF: (data, amortizationSchedule) => {
        if (!window.jspdf) {
            console.error("jsPDF not loaded");
            alert("Error: PDF Library not ready. Please reload.");
            return;
        }
        const { jsPDF } = window.jspdf;
        const doc = new jsPDF();

        // Brand Colors
        const brandColor = [79, 70, 229]; // Indigo 600
        const secondaryColor = [16, 185, 129]; // Emerald 500

        // 1. Header
        doc.setFillColor(...brandColor);
        doc.rect(0, 0, 210, 40, 'F');

        doc.setFont("helvetica", "bold");
        doc.setFontSize(22);
        doc.setTextColor(255, 255, 255);
        doc.text("Smart EMI Report", 14, 25);

        doc.setFontSize(10);
        doc.setFont("helvetica", "normal");
        doc.text("Generated by Smart EMI Pro", 160, 25, { align: 'center' });

        // 2. Loan Summary Section
        doc.setTextColor(0, 0, 0);
        doc.setFontSize(14);
        doc.text("Loan Summary", 14, 55);

        const summaryData = [
            ["Loan Amount", `Rs. ${new Intl.NumberFormat('en-IN').format(data.amount)}`],
            ["Interest Rate", `${data.rate}%`],
            ["Tenure", `${data.tenure} Years`],
            ["Monthly EMI", `Rs. ${new Intl.NumberFormat('en-IN').format(data.emi)}`],
            ["Total Interest", `Rs. ${new Intl.NumberFormat('en-IN').format(data.totalInterest)}`],
            ["Total Payable", `Rs. ${new Intl.NumberFormat('en-IN').format(data.totalPayment)}`]
        ];

        doc.autoTable({
            startY: 60,
            head: [['Description', 'Value']],
            body: summaryData,
            theme: 'grid',
            headStyles: { fillColor: brandColor, textColor: 255, fontStyle: 'bold' },
            bodyStyles: { textColor: 50 },
            columnStyles: {
                0: { fontStyle: 'bold', width: 80 },
                1: { title: 'right' }
            }
        });

        // 3. Amortization Schedule (Yearly)
        let finalY = doc.lastAutoTable.finalY + 15;
        doc.setFontSize(14);
        doc.text("Repayment Schedule (Yearly Breakdown)", 14, finalY);

        const tableRows = amortizationSchedule.map(row => [
            row.year,
            `Rs. ${new Intl.NumberFormat('en-IN').format(row.principal)}`,
            `Rs. ${new Intl.NumberFormat('en-IN').format(row.interest)}`,
            `Rs. ${new Intl.NumberFormat('en-IN').format(row.balance)}`
        ]);

        doc.autoTable({
            startY: finalY + 5,
            head: [['Year', 'Principal Paid', 'Interest Paid', 'Balance Remaining']],
            body: tableRows,
            theme: 'striped',
            headStyles: { fillColor: secondaryColor, textColor: 255 },
            styles: { fontSize: 9 }
        });

        // 4. Footer
        const pageCount = doc.internal.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.setFontSize(8);
            doc.setTextColor(150);
            doc.text(`Page ${i} of ${pageCount} | Generated on ${new Date().toLocaleDateString()}`, 105, 290, { align: 'center' });
        }

        doc.save(`SmartEMI_Report_${Date.now()}.pdf`);
    },

    // Generate Excel (XLSX)
    generateExcel: (data, amortizationSchedule) => {
        const wb = XLSX.utils.book_new();

        // Sheet 1: Summary
        const summaryData = [
            ["Smart EMI - Loan Report"],
            ["Generated On", new Date().toLocaleString()],
            [""],
            ["Loan Amount", data.amount],
            ["Interest Rate (%)", data.rate],
            ["Tenure (Years)", data.tenure],
            ["Monthly EMI", data.emi],
            ["Total Interest", data.totalInterest],
            ["Total Payable", data.totalPayment]
        ];
        const wsSummary = XLSX.utils.aoa_to_sheet(summaryData);
        XLSX.utils.book_append_sheet(wb, wsSummary, "Summary");

        // Sheet 2: Schedule
        const scheduleData = amortizationSchedule.map(item => ({
            "Year": item.year,
            "Principal Paid": item.principal,
            "Interest Paid": item.interest,
            "Balance Remaining": item.balance
        }));
        const wsSchedule = XLSX.utils.json_to_sheet(scheduleData);
        XLSX.utils.book_append_sheet(wb, wsSchedule, "Schedule");

        XLSX.writeFile(wb, `SmartEMI_Data_${Date.now()}.xlsx`);
    },

    // Generate CSV
    generateCSV: (amortizationSchedule) => {
        const worksheet = XLSX.utils.json_to_sheet(amortizationSchedule);
        const csv = XLSX.utils.sheet_to_csv(worksheet);

        const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
        const link = document.createElement("a");
        const url = URL.createObjectURL(blob);
        link.setAttribute("href", url);
        link.setAttribute("download", `SmartEMI_Schedule_${Date.now()}.csv`);
        link.style.visibility = 'hidden';
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
    }
};
